default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],   # the .p8 contents
      is_key_content_base64: false
    )

    match(type: "appstore", readonly: true)

    increment_build_number(xcodeproj: "MakeCampaign.xcodeproj")
    build_app(
      scheme: "MakeCampaign",
      export_method: "app-store"
    )
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      distribute_external: false
    )
  end

  desc "Run unit tests"
  lane :tests do
    scan(
      scheme: "MakeCampaign",
      clean: false,
      only_testing: ["MakeCampaignTests"],
      device: "iPhone 15 Pro",
      result_bundle: true,
      output_directory: "test_output"
    )
  end
  
  
end
